services:
  - type: web
    name: recreio-arcade-g2-demo
    runtime: node
    buildCommand: npm install && npm install --prefix web && npm install --prefix mock-api && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://plataforma-gestao-api.onrender.com/api
